# Add this workflow to any GitHub package repository you want to automatically
# add to the internal-cran drat repo. If a secret for the internal-cran is
# configured, pass the secret via the github-token parameter.

name: Add package to internal-cran

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  internal-cran-upload:
    runs-on: ubuntu-20.04
    name: Internal CRAN Upload
    steps:
      - name: Trigger pkgcheck-action build
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.INTERNAL_CRAN_SECRET }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dragosmg',
              repo: 'internal-cran',
              workflow_id: 'build.yaml',
              ref: 'gh-pages',
              inputs: {
                repo: "${{ github.repository }}",
                pkg_path: "packageA"
              }
            });
