on:
  pull_request:
    types:
      - closed
    branches:
      - main

name: Bump dev version

permissions: read-all

jobs:
  bump-dev-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install {desc}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: desc

      - name: Bump dev version in DESCRIPTION
        run: desc::desc_bump_version("dev", normalize = TRUE)
        shell: Rscript {0}

      - name: Update `Date` field
        run: if (desc::desc_has_fields("Date")) desc::desc_set("Date", Sys.Date())
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit ./DESCRIPTION -m "Bump dev version"
          git pull --ff-only
          git push origin
