on:
  push:
    branches:
      - main

name: Bump dev version ⬆

permissions: read-all

jobs:
  bump-dev-version:
    if: |
      !(contains(github.event.commits[0].message, "[skip version bump]") ||
        contains(github.event.head_commit.message, "[skip version bump]")
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install {desc}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: desc

      - name: Bump dev version in DESCRIPTION
        run: |
          ver <- desc::desc_get_version()
          cat(paste("\nDESCRIPTION version:", ver, "\n"))
          ver_length <- ver |> as.character() |> stringr::str_split("\\.") |> unlist() |> length()
          if (ver_length == 4) desc::desc_bump_version("dev", normalize = TRUE)
          ver <- desc::desc_get_version()
          cat(paste("\nUpdated DESCRIPTION version:", ver, "\n"))
        shell: Rscript {0}

      - name: Record the new package version
        run: |
          DESC_VERSION=$(R --slave -e 'cat(paste(desc::desc_get_version()))' | tr -d '\n' | xargs)
          echo "NEW_PKG_VERSION=${DESC_VERSION}" >> $GITHUB_ENV

      - name: Update `Date` field
        run: if (desc::desc_has_fields("Date")) desc::desc_set("Date", Sys.Date())
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "Github Actions"
          git config --local user.email "$github-actions@users.noreply.github.com"
          git commit ./DESCRIPTION -m "[skip version bump] dev version to ${{ env.NEW_PKG_VERSION }}"
          git pull --ff-only
          git push origin
